SKILL_TAXONOMY = {
    "sql": "SQL",
    "nosql": "NoSQL",
    "python": "Python",
    "tableau": "Tableau",
    "power bi": "Power BI",
    "looker": "Looker",
    "excel": "Microsoft Excel",
    "r": "R",
    "pandas": "Pandas",
    "numpy": "NumPy",
    "scikit-learn": "Scikit-Learn",
    "tensorflow": "TensorFlow",
    "pytorch": "PyTorch",
    "react": "React",
    "vue": "Vue.js",
    "angular": "Angular",
    "typescript": "TypeScript",
    "javascript": "JavaScript",
    "node.js": "Node.js",
    "express": "Express.js",
    "fastapi": "FastAPI",
    "django": "Django",
    "flask": "Flask",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "aws": "AWS",
    "gcp": "Google Cloud Platform",
    "azure": "Azure",
    "kafka": "Apache Kafka",
    "redis": "Redis",
    "postgresql": "PostgreSQL",
    "mongodb": "MongoDB",
    "mysql": "MySQL",
    "git": "Git",
    "figma": "Figma",
    "user research": "User Research",
    "prototyping": "Prototyping",
    "design systems": "Design Systems",
    "usability testing": "Usability Testing",
    "design thinking": "Design Thinking",
    "motion design": "Motion Design",
    "product strategy": "Product Strategy",
    "agile": "Agile",
    "scrum": "Scrum",
    "stakeholder management": "Stakeholder Management",
    "data analysis": "Data Analysis",
    "statistics": "Statistics",
    "machine learning": "Machine Learning",
    "deep learning": "Deep Learning",
    "nlp": "Natural Language Processing",
    "airflow": "Apache Airflow",
    "spark": "Apache Spark",
    "bigquery": "BigQuery",
    "dbt": "dbt",
    "process mapping": "Process Mapping",
    "ci/cd": "CI/CD",
    "rest api": "REST API",
    "graphql": "GraphQL",
    "grpc": "gRPC",
    "html/css": "HTML/CSS",
    "tailwind css": "Tailwind CSS",
    "next.js": "Next.js",
    "product analytics": "Product Analytics",
    "a/b testing": "A/B Testing",
    "motion design": "Motion Design",
    "golang": "Go",
    "elasticsearch": "Elasticsearch",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "helm": "Helm",
    "prometheus": "Prometheus",
    "grafana": "Grafana",
    "kotlin": "Kotlin",
    "swift": "Swift",
    "swiftui": "SwiftUI",
    "flutter": "Flutter",
    "dart": "Dart",
    "java": "Java",
    "spring boot": "Spring Boot",
    "laravel": "Laravel",
    "php": "PHP",
    "soa": "Service-Oriented Architecture",
    "microservices": "Microservices",
    "microservices architecture": "Microservices",
    "rest apis": "REST API",
    "rest api": "REST API",
    "soap": "SOAP",
    "jwt": "JWT",
    "oauth": "OAuth 2.0",
    "rabbitmq": "RabbitMQ",
    "celery": "Celery",
    "mariadb": "MariaDB",
    "couchdb": "CouchDB",
    "dynamodb": "DynamoDB",
    "datadog": "Datadog",
    "new relic": "New Relic",
    "jenkins": "Jenkins",
    "github actions": "GitHub Actions",
    "gitlab ci": "GitLab CI",
    "circleci": "CircleCI",
    "bootstrap": "Bootstrap",
    "jquery": "jQuery",
    "sass": "Sass",
    "less": "Less",
    "webpack": "Webpack",
    "vite": "Vite",
    "eslint": "ESLint",
    "prettier": "Prettier",
    "jest": "Jest",
    "pytest": "pytest",
    "selenium": "Selenium",
    "cypress": "Cypress",
    "storybook": "Storybook",
    "material ui": "Material UI",
    "ant design": "Ant Design",
    "shadcn": "shadcn/ui",
    "react native": "React Native",
    "expo": "Expo",
    "kafka connect": "Apache Kafka",
    "kafka": "Apache Kafka",
}


def normalize_skills(skills: list[str]) -> list[dict]:
    results = []
    for skill in skills:
        key = skill.strip().lower()
        canonical = SKILL_TAXONOMY.get(key, skill.strip())
        results.append({"original": skill.strip(), "canonical": canonical})
    return results
