SKILL_TAXONOMY = {
    "sql": "SQL",
    "nosql": "NoSQL",
    "python": "Python",
    "tableau": "Tableau",
    "power bi": "Power BI",
    "looker": "Looker",
    "excel": "Microsoft Excel",
    "r": "R",
    "pandas": "Pandas",
    "numpy": "NumPy",
    "scikit-learn": "Scikit-Learn",
    "tensorflow": "TensorFlow",
    "pytorch": "PyTorch",
    "react": "React",
    "vue": "Vue.js",
    "angular": "Angular",
    "typescript": "TypeScript",
    "javascript": "JavaScript",
    "node.js": "Node.js",
    "express": "Express.js",
    "fastapi": "FastAPI",
    "django": "Django",
    "flask": "Flask",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "aws": "AWS",
    "gcp": "Google Cloud Platform",
    "azure": "Azure",
    "kafka": "Apache Kafka",
    "redis": "Redis",
    "postgresql": "PostgreSQL",
    "mongodb": "MongoDB",
    "mysql": "MySQL",
    "git": "Git",
    "figma": "Figma",
    "user research": "User Research",
    "prototyping": "Prototyping",
    "design systems": "Design Systems",
    "usability testing": "Usability Testing",
    "design thinking": "Design Thinking",
    "motion design": "Motion Design",
    "product strategy": "Product Strategy",
    "agile": "Agile",
    "scrum": "Scrum",
    "stakeholder management": "Stakeholder Management",
    "data analysis": "Data Analysis",
    "statistics": "Statistics",
    "machine learning": "Machine Learning",
    "deep learning": "Deep Learning",
    "nlp": "Natural Language Processing",
    "airflow": "Apache Airflow",
    "spark": "Apache Spark",
    "bigquery": "BigQuery",
    "dbt": "dbt",
    "process mapping": "Process Mapping",
    "ci/cd": "CI/CD",
    "rest api": "REST API",
    "graphql": "GraphQL",
    "grpc": "gRPC",
    "html/css": "HTML/CSS",
    "tailwind css": "Tailwind CSS",
    "next.js": "Next.js",
    "product analytics": "Product Analytics",
    "a/b testing": "A/B Testing",
    "motion design": "Motion Design",
}


def normalize_skills(skills: list[str]) -> list[dict]:
    results = []
    for skill in skills:
        key = skill.strip().lower()
        canonical = SKILL_TAXONOMY.get(key, skill.strip())
        results.append({"original": skill.strip(), "canonical": canonical})
    return results
