# Generated by Alembic: please review
"""
init: create session table
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import Column, String, Text, JSON

revision = "001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "session",
        Column("id", String, primary_key=True),
        Column("profile", JSON, nullable=True),
        Column("blueprint", JSON, nullable=True),
        Column("status", String, default="pending"),
        Column("created_at", String, nullable=True),
    )


def downgrade():
    op.drop_table("session")
